### ISSUE TITLE
will we want to fine tune permissions beyond a webID can do everything or nothing?

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_acl#7]
that is, we know we're defaulting to:

- anyone can read anything

but the webACL could allow us to have a given webID
- have or not have write permissions for all stuff in the group
- have or not have append permissions for all stuff in the group (?)
- have or not have control permissions for all stuff in the group (?)

which could imply that:
- functions would need to have a way for caller to indicate desired settings for a webID
- CLI would need a way for user to indicate desired settings for a webID
- permissions could be changed for a webID already in the webACL doc, rather than just add or delete

**Comment by jermnelson** [comment]
> that is, we know we're defaulting to:
> 
>     * anyone can read anything
> 
> 
> but the webACL could allow us to have a given webID
> 
>     * have or not have write permissions for all stuff in the group
> 
Yes, we assume all resources created in a group have  acl:Write permissions for all of the stuff in the group.
>     * have or not have append permissions for all stuff in the group (?)
> 
No, I think acl:Write should be used instead of acl:Append based Aaron's comment in this [doc](https://github.com/trellis-ldp/trellis/wiki/Authorization)
>     * have or not have control permissions for all stuff in the group (?)
> 
No, I think only Sinopia Admins (starting with Michelle) should have acl:Control on these group ACL

> which could imply that:
> 
>     * functions would need to have a way for caller to indicate desired settings for a webID
> 
Not sure, I think the only two settings that would be passed into the function would be the username and group at this point or am I missing some nuance? We would need to set Michelle (and other admins) JWT up in an .ENV file.

>     * CLI would need a way for user to indicate desired settings for a webID
> 
We'll have access to the `process.argv` that allow a CLI call like `node src/index.js username group-id` 
>     * permissions could be changed for a webID already in the webACL doc, rather than just add or delete

Since the ACL is a RDF format, we could use N3 to update the acl:Write triples rather than add or delete.

**Comment by ndushay** [comment]
I think I have captured the answers in this ticket with other tickets, so I am closing this one.

- sticking to using `acl:Write` and not `acl:Append` per Christina's exemplars (https://github.com/LD4P/sinopia_server/wiki/Draft-Notes-for-Sinopia-Server-API-Spec)
- #14 only admins should have control group access
- #4 create CLI ... added relevant parts from answers
- #3, #6:  I am planning on using N3Store to edit WebACL in native RDF 
- #5  use JWT for accessTokens: we will use the approach outlined in #5 rather than creating local env vars, as accessTokens for cognito expire after an hour
- we will use `config` package (https://www.npmjs.com/package/config) for configuration vars, rather than .ENV and dotfiles
